# docker build -t oculux314/cares:CrazySim-headless .
# docker run --rm -p 19850:19850/udp --gpus all --name crazysim oculux314/cares:CrazySim-headless
FROM oculux314/cares:CrazySim
WORKDIR /app

# A simple patch to run CrazySim headless
RUN sed -i \
    -e 's/^gz sim -g$/wait/' \
    /app/CrazySim/crazyflie-firmware/tools/crazyflie-simulation/simulator_files/gazebo/launch/sitl_singleagent.sh

CMD ["bash", "-c", "cd /app/CrazySim/crazyflie-firmware && bash tools/crazyflie-simulation/simulator_files/gazebo/launch/sitl_singleagent.sh -m crazyflie -x 0 -y 0"]
